export const LOGIN_SUCCESS_RESPONSE = {
  access_token: 'access_token_example',
  token_type: 'Bearer',
  expires_in: 7200,
  refresh_token: 'refresh_token_example',
  created_at: 1694357628,
};

export const LOGIN_ERROR_RESPONSE = {
  error: 'invalid_grant',
  error_description:
    'The provided authorization grant is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client.',
};

export const SIGN_UP_SUCCESS_RESPONSE = {
  data: {
    id: '7159',
    type: 'user',
    attributes: {
      email: 'user@example.com',
      store_credits: 0,
      completed_orders: 0,
    },
    relationships: {
      default_billing_address: {data: null},
      default_shipping_address: {data: null},
    },
  },
};

export const SIGN_UP_ERROR_RESPONSE = {
  error: 'Email is invalid, Password is too short (minimum is 6 characters)',
  errors: {
    email: ['is invalid'],
    password: ['is too short (minimum is 6 characters)'],
  },
};

export const PRODUCTS_SUCCESS_RESPONSE = {
  data: [
    {
      id: '1',
      type: 'product',
      attributes: {
        name: 'Denim Shirt',
        description:
          'Est cupiditate dolorem tempora cum. Pariatur facilis similique quidem doloremque nemo expedita provident inventore. Odit ratione in tempora consequatur a voluptatum. Nostrum possimus fugit tenetur delectus.',
        available_on: '2021-08-15T04:34:02.280-05:00',
        slug: 'denim-shirt',
        meta_description: null,
        meta_keywords: null,
        updated_at: '2023-08-21T18:04:39.970-05:00',
        sku: 'Shirts_denimshirt_60.99',
        purchasable: true,
        in_stock: true,
        backorderable: false,
        available: true,
        currency: 'USD',
        price: '60.99',
        display_price: '$60.99',
        compare_at_price: null,
        display_compare_at_price: null,
      },
      relationships: {
        variants: {data: [{id: '117', type: 'variant'}]},
        option_types: {
          data: [
            {id: '1', type: 'option_type'},
            {id: '3', type: 'option_type'},
          ],
        },
        product_properties: {
          data: [
            {id: '137', type: 'product_property'},
            {id: '138', type: 'product_property'},
            {id: '139', type: 'product_property'},
            {id: '140', type: 'product_property'},
            {id: '141', type: 'product_property'},
            {id: '142', type: 'product_property'},
            {id: '143', type: 'product_property'},
            {id: '144', type: 'product_property'},
          ],
        },
        taxons: {
          data: [
            {id: '2', type: 'taxon'},
            {id: '5', type: 'taxon'},
          ],
        },
        images: {
          data: [
            {id: '234', type: 'image'},
            {id: '356', type: 'image'},
          ],
        },
        default_variant: {data: {id: '117', type: 'variant'}},
        primary_variant: {data: {id: '1', type: 'variant'}},
      },
    },
    {
      id: '2',
      type: 'product',
      attributes: {
        name: 'Checked Shirt',
        description:
          '\u003cp\u003eItaque ducimus neque esse odit vitae. Nam omnis doloremque officia eum qui dignissimos. Necessitatibus maiores incidunt ullam fugiat ab cumque quo. Rem repellendus maxime odio excepturi labore.\u003c/p\u003e',
        available_on: '2021-08-15T00:00:00.000-05:00',
        slug: 'checked-shirt',
        meta_description: '',
        meta_keywords: '',
        updated_at: '2023-09-04T07:45:25.702-05:00',
        sku: 'Shirts_checkedshirt_47.99',
        purchasable: true,
        in_stock: true,
        backorderable: true,
        available: true,
        currency: 'USD',
        price: '47.99',
        display_price: '$47.99',
        compare_at_price: '0.0',
        display_compare_at_price: '$0.00',
      },
      relationships: {
        variants: {
          data: [
            {id: '118', type: 'variant'},
            {id: '237', type: 'variant'},
          ],
        },
        option_types: {
          data: [
            {id: '1', type: 'option_type'},
            {id: '3', type: 'option_type'},
          ],
        },
        product_properties: {
          data: [
            {id: '233', type: 'product_property'},
            {id: '234', type: 'product_property'},
            {id: '235', type: 'product_property'},
            {id: '236', type: 'product_property'},
            {id: '237', type: 'product_property'},
            {id: '238', type: 'product_property'},
            {id: '239', type: 'product_property'},
            {id: '240', type: 'product_property'},
          ],
        },
        taxons: {
          data: [
            {id: '30', type: 'taxon'},
            {id: '5', type: 'taxon'},
            {id: '20', type: 'taxon'},
            {id: '2', type: 'taxon'},
          ],
        },
        images: {
          data: [
            {id: '217', type: 'image'},
            {id: '216', type: 'image'},
            {id: '348', type: 'image'},
            {id: '349', type: 'image'},
            {id: '351', type: 'image'},
            {id: '350', type: 'image'},
            {id: '352', type: 'image'},
            {id: '353', type: 'image'},
            {id: '355', type: 'image'},
            {id: '354', type: 'image'},
          ],
        },
        default_variant: {data: {id: '118', type: 'variant'}},
        primary_variant: {data: {id: '2', type: 'variant'}},
      },
    },
    {
      id: '3',
      type: 'product',
      attributes: {
        name: 'Covered Placket Shirt',
        description:
          '\u003cp\u003eIncidunt ea reprehenderit perferendis iste. Aut quis tenetur dignissimos ipsa quaerat asperiores amet. Voluptate laborum facere recusandae quae.\u003c/p\u003e',
        available_on: '2021-08-15T00:00:00.000-05:00',
        slug: 'covered-placket-shirt',
        meta_description: '',
        meta_keywords: '',
        updated_at: '2023-08-17T05:43:52.833-05:00',
        sku: 'Shirts_coveredplacketshirt_41.99',
        purchasable: true,
        in_stock: true,
        backorderable: true,
        available: true,
        currency: 'USD',
        price: '41.99',
        display_price: '$41.99',
        compare_at_price: '0.0',
        display_compare_at_price: '$0.00',
      },
      relationships: {
        variants: {
          data: [
            {id: '119', type: 'variant'},
            {id: '270', type: 'variant'},
            {id: '271', type: 'variant'},
          ],
        },
        option_types: {
          data: [
            {id: '1', type: 'option_type'},
            {id: '3', type: 'option_type'},
          ],
        },
        product_properties: {
          data: [
            {id: '211', type: 'product_property'},
            {id: '212', type: 'product_property'},
            {id: '213', type: 'product_property'},
            {id: '214', type: 'product_property'},
            {id: '215', type: 'product_property'},
            {id: '216', type: 'product_property'},
            {id: '217', type: 'product_property'},
            {id: '218', type: 'product_property'},
          ],
        },
        taxons: {
          data: [
            {id: '32', type: 'taxon'},
            {id: '18', type: 'taxon'},
            {id: '2', type: 'taxon'},
            {id: '5', type: 'taxon'},
          ],
        },
        images: {
          data: [
            {id: '21', type: 'image'},
            {id: '30', type: 'image'},
            {id: '31', type: 'image'},
            {id: '160', type: 'image'},
            {id: '161', type: 'image'},
          ],
        },
        default_variant: {data: {id: '119', type: 'variant'}},
        primary_variant: {data: {id: '3', type: 'variant'}},
      },
    },
    {
      id: '4',
      type: 'product',
      attributes: {
        name: 'Slim Fit Shirt',
        description:
          'Rem nostrum voluptatem natus repellat qui placeat. Ex ipsam perspiciatis ipsum quidem suscipit officiis. Eveniet atque saepe nesciunt voluptate iusto culpa architecto. Consequuntur natus vero odio voluptas velit harum alias.',
        available_on: '2021-08-15T04:34:02.900-05:00',
        slug: 'slim-fit-shirt',
        meta_description: null,
        meta_keywords: null,
        updated_at: '2023-06-23T05:04:00.139-05:00',
        sku: 'Shirts_slimfitshirt_47.99',
        purchasable: true,
        in_stock: false,
        backorderable: true,
        available: true,
        currency: 'USD',
        price: '47.99',
        display_price: '$47.99',
        compare_at_price: null,
        display_compare_at_price: null,
      },
      relationships: {
        variants: {data: [{id: '120', type: 'variant'}]},
        option_types: {
          data: [
            {id: '1', type: 'option_type'},
            {id: '3', type: 'option_type'},
          ],
        },
        product_properties: {
          data: [
            {id: '225', type: 'product_property'},
            {id: '226', type: 'product_property'},
            {id: '227', type: 'product_property'},
            {id: '228', type: 'product_property'},
            {id: '229', type: 'product_property'},
            {id: '230', type: 'product_property'},
            {id: '231', type: 'product_property'},
            {id: '232', type: 'product_property'},
          ],
        },
        taxons: {
          data: [
            {id: '21', type: 'taxon'},
            {id: '22', type: 'taxon'},
            {id: '5', type: 'taxon'},
            {id: '2', type: 'taxon'},
          ],
        },
        images: {
          data: [
            {id: '32', type: 'image'},
            {id: '315', type: 'image'},
            {id: '33', type: 'image'},
          ],
        },
        default_variant: {data: {id: '120', type: 'variant'}},
        primary_variant: {data: {id: '4', type: 'variant'}},
      },
    },
    {
      id: '5',
      type: 'product',
      attributes: {
        name: 'Short Sleeve Shirt',
        description:
          'Ab laboriosam eligendi sunt architecto aliquid. Magnam aliquid id esse voluptatum. Itaque necessitatibus hic tempore fuga repudiandae suscipit.',
        available_on: '2021-08-15T04:34:03.078-05:00',
        slug: 'short-sleeve-shirt',
        meta_description: null,
        meta_keywords: null,
        updated_at: '2023-06-23T05:04:00.139-05:00',
        sku: 'Shirts_shortsleeveshirt_79.99',
        purchasable: true,
        in_stock: true,
        backorderable: true,
        available: true,
        currency: 'USD',
        price: '79.99',
        display_price: '$79.99',
        compare_at_price: null,
        display_compare_at_price: null,
      },
      relationships: {
        variants: {data: [{id: '121', type: 'variant'}]},
        option_types: {
          data: [
            {id: '1', type: 'option_type'},
            {id: '3', type: 'option_type'},
          ],
        },
        product_properties: {
          data: [
            {id: '863', type: 'product_property'},
            {id: '864', type: 'product_property'},
            {id: '865', type: 'product_property'},
            {id: '866', type: 'product_property'},
            {id: '867', type: 'product_property'},
            {id: '868', type: 'product_property'},
            {id: '869', type: 'product_property'},
            {id: '870', type: 'product_property'},
          ],
        },
        taxons: {
          data: [
            {id: '22', type: 'taxon'},
            {id: '5', type: 'taxon'},
            {id: '20', type: 'taxon'},
            {id: '2', type: 'taxon'},
          ],
        },
        images: {
          data: [
            {id: '312', type: 'image'},
            {id: '375', type: 'image'},
            {id: '376', type: 'image'},
            {id: '377', type: 'image'},
            {id: '380', type: 'image'},
          ],
        },
        default_variant: {data: {id: '121', type: 'variant'}},
        primary_variant: {data: {id: '5', type: 'variant'}},
      },
    },
    {
      id: '6',
      type: 'product',
      attributes: {
        name: 'Printed Short Sleeve Shirt',
        description:
          'Eius deleniti itaque quos magnam at atque voluptas. Quasi fuga quae dignissimos sequi voluptatem iste laborum. Voluptatibus occaecati debitis illum odit ex vel beatae odio. Iure voluptas harum voluptatibus labore beatae sapiente necessitatibus. Tenetur consectetur ab aliquid cupiditate culpa aspernatur illo atque.',
        available_on: '2021-08-15T04:34:03.253-05:00',
        slug: 'printed-short-sleeve-shirt',
        meta_description: null,
        meta_keywords: null,
        updated_at: '2023-06-23T05:04:00.139-05:00',
        sku: 'Shirts_printedshortsleeveshirt_92.99',
        purchasable: true,
        in_stock: true,
        backorderable: true,
        available: true,
        currency: 'USD',
        price: '92.99',
        display_price: '$92.99',
        compare_at_price: null,
        display_compare_at_price: null,
      },
      relationships: {
        variants: {data: [{id: '122', type: 'variant'}]},
        option_types: {
          data: [
            {id: '1', type: 'option_type'},
            {id: '3', type: 'option_type'},
          ],
        },
        product_properties: {
          data: [
            {id: '171', type: 'product_property'},
            {id: '172', type: 'product_property'},
            {id: '173', type: 'product_property'},
            {id: '174', type: 'product_property'},
            {id: '175', type: 'product_property'},
            {id: '176', type: 'product_property'},
            {id: '177', type: 'product_property'},
            {id: '178', type: 'product_property'},
          ],
        },
        taxons: {
          data: [
            {id: '2', type: 'taxon'},
            {id: '5', type: 'taxon'},
          ],
        },
        images: {
          data: [
            {id: '296', type: 'image'},
            {id: '38', type: 'image'},
            {id: '39', type: 'image'},
          ],
        },
        default_variant: {data: {id: '122', type: 'variant'}},
        primary_variant: {data: {id: '6', type: 'variant'}},
      },
    },
    {
      id: '8',
      type: 'product',
      attributes: {
        name: 'Checked Slim Fit Shirt',
        description:
          '\u003cp\u003eCorporis iste quos veritatis voluptatum praesentium dicta possimus esse. Labore quo incidunt dolore hic aut totam. Doloribus deleniti tempore dicta facilis recusandae unde.\u003c/p\u003e',
        available_on: '2021-08-15T00:00:00.000-05:00',
        slug: 'checked-slim-fit-shirt',
        meta_description: '',
        meta_keywords: '',
        updated_at: '2023-06-23T05:04:00.139-05:00',
        sku: 'Shirts_checkedslimfitshirt_45.99',
        purchasable: true,
        in_stock: true,
        backorderable: true,
        available: true,
        currency: 'USD',
        price: '45.99',
        display_price: '$45.99',
        compare_at_price: '0.0',
        display_compare_at_price: '$0.00',
      },
      relationships: {
        variants: {data: [{id: '124', type: 'variant'}]},
        option_types: {
          data: [
            {id: '1', type: 'option_type'},
            {id: '3', type: 'option_type'},
          ],
        },
        product_properties: {
          data: [
            {id: '871', type: 'product_property'},
            {id: '872', type: 'product_property'},
            {id: '873', type: 'product_property'},
            {id: '874', type: 'product_property'},
            {id: '875', type: 'product_property'},
            {id: '876', type: 'product_property'},
            {id: '877', type: 'product_property'},
            {id: '878', type: 'product_property'},
          ],
        },
        taxons: {
          data: [
            {id: '20', type: 'taxon'},
            {id: '5', type: 'taxon'},
            {id: '2', type: 'taxon'},
            {id: '21', type: 'taxon'},
            {id: '22', type: 'taxon'},
          ],
        },
        images: {data: [{id: '219', type: 'image'}]},
        default_variant: {data: {id: '124', type: 'variant'}},
        primary_variant: {data: {id: '8', type: 'variant'}},
      },
    },
    {
      id: '9',
      type: 'product',
      attributes: {
        name: 'Dotted Shirt',
        description:
          '\u003cp\u003eEnim libero odio quam numquam totam cupiditate repellat quaerat. Ex voluptatem atque repellat iste eveniet saepe accusamus. Ab at dolor consequuntur minus nobis omnis voluptates. Quidem cum laborum quibusdam aliquam architecto voluptatum ipsum. Vero ab nobis iure magnam quod doloribus quos pariatur.\u003c/p\u003e',
        available_on: '2021-08-15T00:00:00.000-05:00',
        slug: 'dotted-shirt',
        meta_description: '',
        meta_keywords: '',
        updated_at: '2023-07-18T05:32:32.468-05:00',
        sku: 'Shirts_dottedshirt_70.99',
        purchasable: true,
        in_stock: true,
        backorderable: true,
        available: true,
        currency: 'USD',
        price: '70.99',
        display_price: '$70.99',
        compare_at_price: '0.0',
        display_compare_at_price: '$0.00',
      },
      relationships: {
        variants: {data: [{id: '125', type: 'variant'}]},
        option_types: {
          data: [
            {id: '1', type: 'option_type'},
            {id: '3', type: 'option_type'},
          ],
        },
        product_properties: {
          data: [
            {id: '179', type: 'product_property'},
            {id: '180', type: 'product_property'},
            {id: '181', type: 'product_property'},
            {id: '182', type: 'product_property'},
            {id: '183', type: 'product_property'},
            {id: '184', type: 'product_property'},
            {id: '185', type: 'product_property'},
            {id: '186', type: 'product_property'},
          ],
        },
        taxons: {
          data: [
            {id: '18', type: 'taxon'},
            {id: '19', type: 'taxon'},
            {id: '5', type: 'taxon'},
            {id: '2', type: 'taxon'},
          ],
        },
        images: {data: [{id: '235', type: 'image'}]},
        default_variant: {data: {id: '125', type: 'variant'}},
        primary_variant: {data: {id: '9', type: 'variant'}},
      },
    },
    {
      id: '10',
      type: 'product',
      attributes: {
        name: 'Linen Shirt',
        description:
          'Totam quae placeat cum facilis officia. Aut mollitia quis consequatur unde error ratione explicabo. Vel architecto eligendi quas dignissimos tempore eveniet. Exercitationem iste saepe in praesentium aliquid dignissimos. Tenetur ad commodi tempora eligendi quam non odit.',
        available_on: '2021-08-15T04:34:03.894-05:00',
        slug: 'linen-shirt',
        meta_description: null,
        meta_keywords: null,
        updated_at: '2023-06-23T05:04:00.139-05:00',
        sku: 'Shirts_linenshirt_89.99',
        purchasable: true,
        in_stock: true,
        backorderable: true,
        available: true,
        currency: 'USD',
        price: '89.99',
        display_price: '$89.99',
        compare_at_price: null,
        display_compare_at_price: null,
      },
      relationships: {
        variants: {data: [{id: '126', type: 'variant'}]},
        option_types: {
          data: [
            {id: '1', type: 'option_type'},
            {id: '3', type: 'option_type'},
          ],
        },
        product_properties: {
          data: [
            {id: '187', type: 'product_property'},
            {id: '188', type: 'product_property'},
            {id: '189', type: 'product_property'},
            {id: '190', type: 'product_property'},
            {id: '191', type: 'product_property'},
            {id: '192', type: 'product_property'},
            {id: '193', type: 'product_property'},
            {id: '194', type: 'product_property'},
          ],
        },
        taxons: {
          data: [
            {id: '21', type: 'taxon'},
            {id: '5', type: 'taxon'},
            {id: '2', type: 'taxon'},
          ],
        },
        images: {data: [{id: '270', type: 'image'}]},
        default_variant: {data: {id: '126', type: 'variant'}},
        primary_variant: {data: {id: '10', type: 'variant'}},
      },
    },
    {
      id: '12',
      type: 'product',
      attributes: {
        name: 'Polo T Shirt',
        description:
          '\u003cp\u003eQuis occaecati non accusantium dolor deleniti delectus inventore deserunt. Aut necessitatibus natus tempore nam nihil numquam ullam doloremque. Unde dolore incidunt mollitia placeat fugiat suscipit.\u003c/p\u003e',
        available_on: '2021-08-25T00:00:00.000-05:00',
        slug: 'polo-t-shirt',
        meta_description: '',
        meta_keywords: '',
        updated_at: '2023-09-06T11:34:10.602-05:00',
        sku: 'T-shirts_polot-shirt_10.99',
        purchasable: true,
        in_stock: true,
        backorderable: true,
        available: true,
        currency: 'USD',
        price: '10.99',
        display_price: '$10.99',
        compare_at_price: '0.0',
        display_compare_at_price: '$0.00',
      },
      relationships: {
        variants: {data: [{id: '128', type: 'variant'}]},
        option_types: {
          data: [
            {id: '1', type: 'option_type'},
            {id: '3', type: 'option_type'},
          ],
        },
        product_properties: {
          data: [
            {id: '1', type: 'product_property'},
            {id: '2', type: 'product_property'},
            {id: '3', type: 'product_property'},
            {id: '4', type: 'product_property'},
            {id: '5', type: 'product_property'},
            {id: '6', type: 'product_property'},
            {id: '7', type: 'product_property'},
            {id: '8', type: 'product_property'},
            {id: '893', type: 'product_property'},
            {id: '894', type: 'product_property'},
          ],
        },
        taxons: {
          data: [
            {id: '30', type: 'taxon'},
            {id: '20', type: 'taxon'},
            {id: '2', type: 'taxon'},
            {id: '6', type: 'taxon'},
          ],
        },
        images: {data: [{id: '291', type: 'image'}]},
        default_variant: {data: {id: '128', type: 'variant'}},
        primary_variant: {data: {id: '12', type: 'variant'}},
      },
    },
    {
      id: '13',
      type: 'product',
      attributes: {
        name: 'Long Sleeve T Shirt',
        description:
          'Similique neque ad eveniet necessitatibus. Voluptates libero a recusandae saepe amet incidunt. Quibusdam officiis repellat vel suscipit nisi. Aspernatur delectus maiores iste nesciunt quod harum. At voluptatem dolorum vel dolorem voluptas.',
        available_on: '2021-08-15T04:34:04.380-05:00',
        slug: 'long-sleeve-t-shirt',
        meta_description: null,
        meta_keywords: null,
        updated_at: '2023-08-21T23:54:48.617-05:00',
        sku: 'T-shirts_longsleevet-shirt_91.99',
        purchasable: true,
        in_stock: true,
        backorderable: true,
        available: true,
        currency: 'USD',
        price: '91.99',
        display_price: '$91.99',
        compare_at_price: null,
        display_compare_at_price: null,
      },
      relationships: {
        variants: {data: [{id: '129', type: 'variant'}]},
        option_types: {
          data: [
            {id: '1', type: 'option_type'},
            {id: '3', type: 'option_type'},
          ],
        },
        product_properties: {
          data: [
            {id: '9', type: 'product_property'},
            {id: '10', type: 'product_property'},
            {id: '11', type: 'product_property'},
            {id: '12', type: 'product_property'},
            {id: '13', type: 'product_property'},
            {id: '14', type: 'product_property'},
            {id: '15', type: 'product_property'},
            {id: '16', type: 'product_property'},
            {id: '813', type: 'product_property'},
            {id: '814', type: 'product_property'},
          ],
        },
        taxons: {
          data: [
            {id: '19', type: 'taxon'},
            {id: '20', type: 'taxon'},
            {id: '2', type: 'taxon'},
            {id: '6', type: 'taxon'},
          ],
        },
        images: {data: [{id: '278', type: 'image'}]},
        default_variant: {data: {id: '129', type: 'variant'}},
        primary_variant: {data: {id: '13', type: 'variant'}},
      },
    },
    {
      id: '14',
      type: 'product',
      attributes: {
        name: '3 4 Sleeve T Shirt',
        description:
          '\u003cp\u003eQuia quidem architecto nobis illum. Ducimus ipsam laudantium animi id hic quibusdam. Praesentium qui saepe enim optio dicta. Dolorum veniam perspiciatis nobis numquam magnam. Ipsam libero quisquam excepturi eum itaque.\u003c/p\u003e',
        available_on: '2021-08-15T00:00:00.000-05:00',
        slug: '3-4-sleeve-t-shirt',
        meta_description: '',
        meta_keywords: '',
        updated_at: '2023-09-06T11:34:10.462-05:00',
        sku: 'T-shirts_3_4sleevet-shirt_97.99',
        purchasable: true,
        in_stock: true,
        backorderable: true,
        available: true,
        currency: 'USD',
        price: '97.99',
        display_price: '$97.99',
        compare_at_price: '0.0',
        display_compare_at_price: '$0.00',
      },
      relationships: {
        variants: {
          data: [
            {id: '130', type: 'variant'},
            {id: '234', type: 'variant'},
          ],
        },
        option_types: {
          data: [
            {id: '1', type: 'option_type'},
            {id: '3', type: 'option_type'},
          ],
        },
        product_properties: {
          data: [
            {id: '888', type: 'product_property'},
            {id: '17', type: 'product_property'},
            {id: '18', type: 'product_property'},
            {id: '19', type: 'product_property'},
            {id: '20', type: 'product_property'},
            {id: '21', type: 'product_property'},
            {id: '22', type: 'product_property'},
            {id: '23', type: 'product_property'},
            {id: '24', type: 'product_property'},
            {id: '887', type: 'product_property'},
          ],
        },
        taxons: {
          data: [
            {id: '20', type: 'taxon'},
            {id: '2', type: 'taxon'},
            {id: '6', type: 'taxon'},
          ],
        },
        images: {
          data: [
            {id: '203', type: 'image'},
            {id: '204', type: 'image'},
          ],
        },
        default_variant: {data: {id: '130', type: 'variant'}},
        primary_variant: {data: {id: '14', type: 'variant'}},
      },
    },
    {
      id: '15',
      type: 'product',
      attributes: {
        name: 'T Shirt With Holes',
        description:
          'Ullam commodi id nihil quo rem. Soluta quo blanditiis laboriosam odio reiciendis aliquam velit. Error ab soluta voluptas delectus. Similique veniam velit voluptatum enim eaque.',
        available_on: '2021-08-15T04:34:04.700-05:00',
        slug: 't-shirt-with-holes',
        meta_description: null,
        meta_keywords: null,
        updated_at: '2023-06-23T05:04:00.139-05:00',
        sku: 'T-shirts_t-shirtwithholes_51.99',
        purchasable: true,
        in_stock: true,
        backorderable: true,
        available: true,
        currency: 'USD',
        price: '51.99',
        display_price: '$51.99',
        compare_at_price: null,
        display_compare_at_price: null,
      },
      relationships: {
        variants: {data: [{id: '131', type: 'variant'}]},
        option_types: {
          data: [
            {id: '1', type: 'option_type'},
            {id: '3', type: 'option_type'},
          ],
        },
        product_properties: {
          data: [
            {id: '25', type: 'product_property'},
            {id: '26', type: 'product_property'},
            {id: '27', type: 'product_property'},
            {id: '28', type: 'product_property'},
            {id: '29', type: 'product_property'},
            {id: '30', type: 'product_property'},
            {id: '31', type: 'product_property'},
            {id: '32', type: 'product_property'},
            {id: '221', type: 'product_property'},
            {id: '222', type: 'product_property'},
          ],
        },
        taxons: {
          data: [
            {id: '2', type: 'taxon'},
            {id: '22', type: 'taxon'},
            {id: '6', type: 'taxon'},
          ],
        },
        images: {data: [{id: '330', type: 'image'}]},
        default_variant: {data: {id: '131', type: 'variant'}},
        primary_variant: {data: {id: '15', type: 'variant'}},
      },
    },
    {
      id: '16',
      type: 'product',
      attributes: {
        name: 'Raw Edge T Shirt',
        description:
          'Dolor saepe tempora voluptatum eum voluptates tenetur sed. Iusto et repellendus velit odio corporis quas. In error excepturi eos aspernatur.',
        available_on: '2021-08-15T04:34:04.854-05:00',
        slug: 'raw-edge-t-shirt',
        meta_description: null,
        meta_keywords: null,
        updated_at: '2023-07-11T18:46:01.552-05:00',
        sku: 'T-shirts_raw-edget-shirt_76.99',
        purchasable: true,
        in_stock: true,
        backorderable: true,
        available: true,
        currency: 'USD',
        price: '76.99',
        display_price: '$76.99',
        compare_at_price: null,
        display_compare_at_price: null,
      },
      relationships: {
        variants: {data: [{id: '132', type: 'variant'}]},
        option_types: {
          data: [
            {id: '1', type: 'option_type'},
            {id: '3', type: 'option_type'},
          ],
        },
        product_properties: {
          data: [
            {id: '33', type: 'product_property'},
            {id: '34', type: 'product_property'},
            {id: '35', type: 'product_property'},
            {id: '36', type: 'product_property'},
            {id: '37', type: 'product_property'},
            {id: '38', type: 'product_property'},
            {id: '39', type: 'product_property'},
            {id: '40', type: 'product_property'},
            {id: '223', type: 'product_property'},
            {id: '224', type: 'product_property'},
          ],
        },
        taxons: {
          data: [
            {id: '22', type: 'taxon'},
            {id: '2', type: 'taxon'},
            {id: '6', type: 'taxon'},
          ],
        },
        images: {data: [{id: '300', type: 'image'}]},
        default_variant: {data: {id: '132', type: 'variant'}},
        primary_variant: {data: {id: '16', type: 'variant'}},
      },
    },
    {
      id: '17',
      type: 'product',
      attributes: {
        name: 'V Neck T Shirt',
        description:
          'Illum quisquam enim blanditiis nam impedit est. Provident error harum atque officiis quia. Rem perspiciatis ratione doloribus minima quibusdam labore. Libero sed temporibus ratione eos inventore.',
        available_on: '2021-08-15T04:34:05.013-05:00',
        slug: 'v-neck-t-shirt',
        meta_description: null,
        meta_keywords: null,
        updated_at: '2023-06-23T05:04:00.139-05:00',
        sku: 'T-shirts_v-neckt-shirt_48.99',
        purchasable: true,
        in_stock: true,
        backorderable: true,
        available: true,
        currency: 'USD',
        price: '48.99',
        display_price: '$48.99',
        compare_at_price: null,
        display_compare_at_price: null,
      },
      relationships: {
        variants: {data: [{id: '133', type: 'variant'}]},
        option_types: {
          data: [
            {id: '1', type: 'option_type'},
            {id: '3', type: 'option_type'},
          ],
        },
        product_properties: {
          data: [
            {id: '41', type: 'product_property'},
            {id: '42', type: 'product_property'},
            {id: '43', type: 'product_property'},
            {id: '44', type: 'product_property'},
            {id: '45', type: 'product_property'},
            {id: '46', type: 'product_property'},
            {id: '47', type: 'product_property'},
            {id: '48', type: 'product_property'},
            {id: '145', type: 'product_property'},
            {id: '146', type: 'product_property'},
          ],
        },
        taxons: {
          data: [
            {id: '2', type: 'taxon'},
            {id: '6', type: 'taxon'},
          ],
        },
        images: {data: [{id: '334', type: 'image'}]},
        default_variant: {data: {id: '133', type: 'variant'}},
        primary_variant: {data: {id: '17', type: 'variant'}},
      },
    },
    {
      id: '18',
      type: 'product',
      attributes: {
        name: 'Tank Top',
        description:
          'Iure modi facilis vel eaque. Natus dolore vitae officia eum sequi unde quos nesciunt. Delectus sit temporibus optio nam nihil consequatur est perspiciatis. Neque amet labore ipsum iusto. Quidem delectus voluptas ab voluptate exercitationem eaque facilis.',
        available_on: '2021-08-15T04:34:05.172-05:00',
        slug: 'tank-top',
        meta_description: null,
        meta_keywords: null,
        updated_at: '2023-06-23T05:04:00.139-05:00',
        sku: 'T-shirts_tanktop_79.99',
        purchasable: true,
        in_stock: true,
        backorderable: true,
        available: true,
        currency: 'USD',
        price: '79.99',
        display_price: '$79.99',
        compare_at_price: null,
        display_compare_at_price: null,
      },
      relationships: {
        variants: {data: [{id: '134', type: 'variant'}]},
        option_types: {
          data: [
            {id: '1', type: 'option_type'},
            {id: '3', type: 'option_type'},
          ],
        },
        product_properties: {
          data: [
            {id: '49', type: 'product_property'},
            {id: '50', type: 'product_property'},
            {id: '51', type: 'product_property'},
            {id: '52', type: 'product_property'},
            {id: '53', type: 'product_property'},
            {id: '54', type: 'product_property'},
            {id: '55', type: 'product_property'},
            {id: '56', type: 'product_property'},
            {id: '219', type: 'product_property'},
            {id: '220', type: 'product_property'},
          ],
        },
        taxons: {
          data: [
            {id: '22', type: 'taxon'},
            {id: '2', type: 'taxon'},
            {id: '6', type: 'taxon'},
          ],
        },
        images: {data: [{id: '329', type: 'image'}]},
        default_variant: {data: {id: '134', type: 'variant'}},
        primary_variant: {data: {id: '18', type: 'variant'}},
      },
    },
    {
      id: '19',
      type: 'product',
      attributes: {
        name: 'Basic T Shirt',
        description:
          '\u003cp\u003eIllo assumenda\u003ca href="../../../products/blouse-with-wide-flounced-sleeve" target="_blank" rel="noopener"\u003e asperio\u003c/a\u003eres reicien\u003cem\u003edis recusandae nemo facere officia est. Placeat porro rem necessitatibus dicta. Adipisc\u003cspan style="color: #f1c40f;"\u003ei repellendus voluptas sunt doloremque consectetur. Praesentium nece\u003c/span\u003e\u003c/em\u003e\u003cspan style="color: #f1c40f;"\u003essitatib\u003c/span\u003eus beatae provident nobis accusamus nemo\u003cstrong\u003e aspernatur ipsa.\u003c/strong\u003e\u003c/p\u003e',
        available_on: '2021-08-15T00:00:00.000-05:00',
        slug: 'basic-t-shirt',
        meta_description: '',
        meta_keywords: '',
        updated_at: '2023-06-23T05:04:00.139-05:00',
        sku: 'T-shirts_basict-shirt_99.99',
        purchasable: true,
        in_stock: true,
        backorderable: true,
        available: true,
        currency: 'USD',
        price: '99.99',
        display_price: '$99.99',
        compare_at_price: '0.0',
        display_compare_at_price: '$0.00',
      },
      relationships: {
        variants: {
          data: [
            {id: '135', type: 'variant'},
            {id: '298', type: 'variant'},
            {id: '299', type: 'variant'},
            {id: '236', type: 'variant'},
          ],
        },
        option_types: {
          data: [
            {id: '1', type: 'option_type'},
            {id: '3', type: 'option_type'},
          ],
        },
        product_properties: {
          data: [
            {id: '57', type: 'product_property'},
            {id: '58', type: 'product_property'},
            {id: '59', type: 'product_property'},
            {id: '60', type: 'product_property'},
            {id: '61', type: 'product_property'},
            {id: '62', type: 'product_property'},
            {id: '63', type: 'product_property'},
            {id: '64', type: 'product_property'},
            {id: '959', type: 'product_property'},
            {id: '960', type: 'product_property'},
          ],
        },
        taxons: {
          data: [
            {id: '2', type: 'taxon'},
            {id: '6', type: 'taxon'},
          ],
        },
        images: {
          data: [
            {id: '213', type: 'image'},
            {id: '382', type: 'image'},
            {id: '383', type: 'image'},
            {id: '148', type: 'image'},
          ],
        },
        default_variant: {data: {id: '135', type: 'variant'}},
        primary_variant: {data: {id: '19', type: 'variant'}},
      },
    },
    {
      id: '20',
      type: 'product',
      attributes: {
        name: 'High Neck Sweater',
        description:
          'Tempore culpa quia illo quod reprehenderit architecto ea ad. Quidem impedit quia ipsa nostrum inventore. Quod minus totam deserunt iste officiis quas consequatur.',
        available_on: '2021-08-15T04:34:05.506-05:00',
        slug: 'high-neck-sweater',
        meta_description: null,
        meta_keywords: null,
        updated_at: '2023-09-06T11:12:58.507-05:00',
        sku: 'Sweaters_highnecksweater_33.99',
        purchasable: true,
        in_stock: true,
        backorderable: true,
        available: true,
        currency: 'USD',
        price: '33.99',
        display_price: '$33.99',
        compare_at_price: null,
        display_compare_at_price: null,
      },
      relationships: {
        variants: {data: [{id: '136', type: 'variant'}]},
        option_types: {
          data: [
            {id: '1', type: 'option_type'},
            {id: '3', type: 'option_type'},
          ],
        },
        product_properties: {
          data: [
            {id: '155', type: 'product_property'},
            {id: '156', type: 'product_property'},
            {id: '157', type: 'product_property'},
            {id: '158', type: 'product_property'},
            {id: '159', type: 'product_property'},
            {id: '160', type: 'product_property'},
            {id: '161', type: 'product_property'},
            {id: '162', type: 'product_property'},
          ],
        },
        taxons: {
          data: [
            {id: '7', type: 'taxon'},
            {id: '18', type: 'taxon'},
            {id: '2', type: 'taxon'},
          ],
        },
        images: {data: [{id: '259', type: 'image'}]},
        default_variant: {data: {id: '136', type: 'variant'}},
        primary_variant: {data: {id: '20', type: 'variant'}},
      },
    },
    {
      id: '21',
      type: 'product',
      attributes: {
        name: 'Stripped Jumper',
        description:
          'Veritatis deserunt soluta consequatur deleniti. Aut id voluptate facilis magni eius hic. Amet laborum quo corporis consequuntur eius alias. Impedit eligendi quia nemo deleniti nulla iusto dolore vel.',
        available_on: '2021-08-15T04:34:05.660-05:00',
        slug: 'stripped-jumper',
        meta_description: null,
        meta_keywords: null,
        updated_at: '2023-07-28T04:14:48.115-05:00',
        sku: 'Sweaters_strippedjumper_36.99',
        purchasable: true,
        in_stock: true,
        backorderable: true,
        available: true,
        currency: 'USD',
        price: '36.99',
        display_price: '$36.99',
        compare_at_price: null,
        display_compare_at_price: null,
      },
      relationships: {
        variants: {data: [{id: '137', type: 'variant'}]},
        option_types: {
          data: [
            {id: '1', type: 'option_type'},
            {id: '3', type: 'option_type'},
          ],
        },
        product_properties: {
          data: [
            {id: '163', type: 'product_property'},
            {id: '164', type: 'product_property'},
            {id: '165', type: 'product_property'},
            {id: '166', type: 'product_property'},
            {id: '167', type: 'product_property'},
            {id: '168', type: 'product_property'},
            {id: '169', type: 'product_property'},
            {id: '170', type: 'product_property'},
          ],
        },
        taxons: {
          data: [
            {id: '7', type: 'taxon'},
            {id: '21', type: 'taxon'},
            {id: '2', type: 'taxon'},
          ],
        },
        images: {data: [{id: '327', type: 'image'}]},
        default_variant: {data: {id: '137', type: 'variant'}},
        primary_variant: {data: {id: '21', type: 'variant'}},
      },
    },
    {
      id: '22',
      type: 'product',
      attributes: {
        name: 'Long Sleeve Jumper With Pocket',
        description:
          'Animi sapiente rerum blanditiis possimus aliquid ab distinctio id. Magnam nisi sit qui voluptatum consequatur tenetur illo minus. Rerum incidunt eveniet ab quod nulla hic inventore quisquam.',
        available_on: '2021-08-15T04:34:05.818-05:00',
        slug: 'long-sleeve-jumper-with-pocket',
        meta_description: null,
        meta_keywords: null,
        updated_at: '2023-06-23T05:04:00.139-05:00',
        sku: 'Sweaters_longsleevejumperwithpocket_52.99',
        purchasable: true,
        in_stock: true,
        backorderable: true,
        available: true,
        currency: 'USD',
        price: '52.99',
        display_price: '$52.99',
        compare_at_price: null,
        display_compare_at_price: null,
      },
      relationships: {
        variants: {data: [{id: '138', type: 'variant'}]},
        option_types: {
          data: [
            {id: '1', type: 'option_type'},
            {id: '3', type: 'option_type'},
          ],
        },
        product_properties: {
          data: [
            {id: '203', type: 'product_property'},
            {id: '204', type: 'product_property'},
            {id: '205', type: 'product_property'},
            {id: '206', type: 'product_property'},
            {id: '207', type: 'product_property'},
            {id: '208', type: 'product_property'},
            {id: '209', type: 'product_property'},
            {id: '210', type: 'product_property'},
          ],
        },
        taxons: {
          data: [
            {id: '7', type: 'taxon'},
            {id: '19', type: 'taxon'},
            {id: '22', type: 'taxon'},
            {id: '2', type: 'taxon'},
          ],
        },
        images: {data: [{id: '272', type: 'image'}]},
        default_variant: {data: {id: '138', type: 'variant'}},
        primary_variant: {data: {id: '22', type: 'variant'}},
      },
    },
  ],
  meta: {
    count: 20,
    total_count: 110,
    total_pages: 6,
    filters: {
      option_types: [
        {
          id: 1,
          name: 'color',
          presentation: 'Color',
          option_values: [
            {id: 2, name: 'purple', presentation: '#800080', position: 2},
            {id: 8, name: 'orange', presentation: '#FF8800', position: 8},
            {id: 19, name: 'ecru', presentation: '#F4F2D6', position: 19},
            {id: 12, name: 'blue', presentation: '#0000FF', position: 12},
            {id: 5, name: 'brown', presentation: '#8B4513', position: 5},
            {id: 1, name: 'white', presentation: '#FFFFFF', position: 1},
            {id: 10, name: 'beige', presentation: '#E1C699', position: 10},
            {id: 3, name: 'red', presentation: '#FF0000', position: 3},
            {id: 14, name: 'khaki', presentation: '#BDB76B', position: 14},
            {id: 13, name: 'dark_blue', presentation: '#00008b', position: 13},
            {id: 16, name: 'light_blue', presentation: '#add8e6', position: 16},
            {id: 17, name: 'pink', presentation: '#FFA6C9', position: 17},
            {id: 9, name: 'burgundy', presentation: '#A8003B', position: 9},
            {id: 7, name: 'grey', presentation: '#808080', position: 7},
            {id: 4, name: 'black', presentation: '#000000', position: 4},
            {id: 11, name: 'mint', presentation: '#AAF0D1', position: 11},
            {id: 6, name: 'green', presentation: '#228C22', position: 6},
          ],
        },
        {
          id: 3,
          name: 'size',
          presentation: 'Size',
          option_values: [
            {id: 25, name: 'm', presentation: 'M', position: 3},
            {id: 24, name: 's', presentation: 'S', position: 2},
            {id: 23, name: 'xs', presentation: 'XS', position: 1},
            {id: 26, name: 'l', presentation: 'L', position: 4},
          ],
        },
        {
          id: 2,
          name: 'length',
          presentation: 'Length',
          option_values: [
            {id: 21, name: 'midi', presentation: 'Midi', position: 2},
            {id: 20, name: 'mini', presentation: 'Mini', position: 1},
          ],
        },
      ],
      product_properties: [
        {
          id: 1,
          name: 'manufacturer',
          presentation: 'Manufacturer',
          values: [
            {value: 'Conditioned', filter_param: 'conditioned'},
            {value: 'Jerseys', filter_param: 'jerseys'},
            {value: 'Resiliance', filter_param: 'resiliance'},
            {value: 'Wannabe', filter_param: 'wannabe'},
            {value: 'Wilson', filter_param: 'wilson'},
          ],
        },
        {
          id: 2,
          name: 'brand',
          presentation: 'Brand',
          values: [
            {value: 'Alpha', filter_param: 'alpha'},
            {value: 'Beta', filter_param: 'beta'},
            {value: 'Delta', filter_param: 'delta'},
            {value: 'Epsilon', filter_param: 'epsilon'},
            {value: 'Gamma', filter_param: 'gamma'},
            {value: 'Theta', filter_param: 'theta'},
            {value: 'Zeta', filter_param: 'zeta'},
          ],
        },
      ],
    },
  },
  links: {
    self: 'https://demo.spreecommerce.org/api/v2/storefront/products?per_page=20\u0026page=1',
    next: 'https://demo.spreecommerce.org/api/v2/storefront/products?page=2\u0026per_page=20',
    prev: 'https://demo.spreecommerce.org/api/v2/storefront/products?page=1\u0026per_page=20',
    last: 'https://demo.spreecommerce.org/api/v2/storefront/products?page=6\u0026per_page=20',
    first:
      'https://demo.spreecommerce.org/api/v2/storefront/products?page=1\u0026per_page=20',
  },
};

export const PRODUCT_SUCCESS_RESPONSE = {
  data: {
    id: '1',
    type: 'product',
    attributes: {
      name: 'Denim Shirt',
      description:
        'Est cupiditate dolorem tempora cum. Pariatur facilis similique quidem doloremque nemo expedita provident inventore. Odit ratione in tempora consequatur a voluptatum. Nostrum possimus fugit tenetur delectus.',
      available_on: '2021-08-15T04:34:02.280-05:00',
      slug: 'denim-shirt',
      meta_description: null,
      meta_keywords: null,
      updated_at: '2023-08-21T18:04:39.970-05:00',
      sku: 'Shirts_denimshirt_60.99',
      purchasable: true,
      in_stock: true,
      backorderable: false,
      available: true,
      currency: 'USD',
      price: '60.99',
      display_price: '$60.99',
      compare_at_price: null,
      display_compare_at_price: null,
    },
    relationships: {
      variants: {data: [{id: '117', type: 'variant'}]},
      option_types: {
        data: [
          {id: '1', type: 'option_type'},
          {id: '3', type: 'option_type'},
        ],
      },
      product_properties: {
        data: [
          {id: '137', type: 'product_property'},
          {id: '138', type: 'product_property'},
          {id: '139', type: 'product_property'},
          {id: '140', type: 'product_property'},
          {id: '141', type: 'product_property'},
          {id: '142', type: 'product_property'},
          {id: '143', type: 'product_property'},
          {id: '144', type: 'product_property'},
        ],
      },
      taxons: {
        data: [
          {id: '2', type: 'taxon'},
          {id: '5', type: 'taxon'},
        ],
      },
      images: {
        data: [
          {id: '234', type: 'image'},
          {id: '356', type: 'image'},
        ],
      },
      default_variant: {data: {id: '117', type: 'variant'}},
      primary_variant: {data: {id: '1', type: 'variant'}},
    },
  },
};

export const ADD_TO_CART_SUCCESS_RESPONSE = {
  data: {
    id: '57157',
    type: 'cart',
    attributes: {
      number: 'R344532313',
      item_total: '1229.8',
      total: '1229.8',
      ship_total: '0.0',
      adjustment_total: '0.0',
      created_at: '2023-08-23T17:30:53.918-05:00',
      updated_at: '2023-09-11T11:51:56.625-05:00',
      completed_at: null,
      included_tax_total: '0.0',
      additional_tax_total: '0.0',
      display_additional_tax_total: '$0.00',
      display_included_tax_total: '$0.00',
      tax_total: '0.0',
      currency: 'USD',
      state: 'address',
      token: 'token_example',
      email: 'john@snow.org',
      display_item_total: '$1,229.80',
      display_ship_total: '$0.00',
      display_adjustment_total: '$0.00',
      display_tax_total: '$0.00',
      promo_total: '0.0',
      display_promo_total: '$0.00',
      item_count: 20,
      special_instructions: null,
      display_total: '$1,229.80',
      pre_tax_item_amount: '1229.8',
      display_pre_tax_item_amount: '$1,229.80',
      pre_tax_total: '1229.8',
      display_pre_tax_total: '$1,229.80',
      shipment_state: null,
      payment_state: null,
    },
    relationships: {
      line_items: {
        data: [
          {id: '32580', type: 'line_item'},
          {
            id: '32581',
            type: 'line_item',
          },
          {id: '32659', type: 'line_item'},
          {id: '32665', type: 'line_item'},
          {
            id: '32668',
            type: 'line_item',
          },
          {id: '32669', type: 'line_item'},
          {id: '32816', type: 'line_item'},
        ],
      },
      variants: {
        data: [
          {id: '19', type: 'variant'},
          {id: '21', type: 'variant'},
          {
            id: '3',
            type: 'variant',
          },
          {id: '13', type: 'variant'},
          {id: '16', type: 'variant'},
          {
            id: '12',
            type: 'variant',
          },
          {id: '1', type: 'variant'},
        ],
      },
      promotions: {data: []},
      payments: {data: []},
      shipments: {data: []},
      user: {data: {id: '7026', type: 'user'}},
      billing_address: {data: {id: '107786', type: 'address'}},
      shipping_address: {data: {id: '107787', type: 'address'}},
    },
  },
  included: [
    {
      id: '32580',
      type: 'line_item',
      attributes: {
        name: 'Basic T Shirt',
        quantity: 4,
        price: '99.99',
        slug: 'basic-t-shirt',
        options_text: '',
        currency: 'USD',
        display_price: '$99.99',
        total: '399.96',
        display_total: '$399.96',
        adjustment_total: '0.0',
        display_adjustment_total: '$0.00',
        additional_tax_total: '0.0',
        discounted_amount: '399.96',
        display_discounted_amount: '$399.96',
        display_additional_tax_total: '$0.00',
        promo_total: '0.0',
        display_promo_total: '$0.00',
        included_tax_total: '0.0',
        display_included_tax_total: '$0.00',
        pre_tax_amount: '399.96',
        display_pre_tax_amount: '$399.96',
      },
      relationships: {variant: {data: {id: '19', type: 'variant'}}},
    },
    {
      id: '32581',
      type: 'line_item',
      attributes: {
        name: 'Stripped Jumper',
        quantity: 2,
        price: '36.99',
        slug: 'stripped-jumper',
        options_text: '',
        currency: 'USD',
        display_price: '$36.99',
        total: '73.98',
        display_total: '$73.98',
        adjustment_total: '0.0',
        display_adjustment_total: '$0.00',
        additional_tax_total: '0.0',
        discounted_amount: '73.98',
        display_discounted_amount: '$73.98',
        display_additional_tax_total: '$0.00',
        promo_total: '0.0',
        display_promo_total: '$0.00',
        included_tax_total: '0.0',
        display_included_tax_total: '$0.00',
        pre_tax_amount: '73.98',
        display_pre_tax_amount: '$73.98',
      },
      relationships: {variant: {data: {id: '21', type: 'variant'}}},
    },
    {
      id: '32659',
      type: 'line_item',
      attributes: {
        name: 'Covered Placket Shirt',
        quantity: 2,
        price: '41.99',
        slug: 'covered-placket-shirt',
        options_text: '',
        currency: 'USD',
        display_price: '$41.99',
        total: '83.98',
        display_total: '$83.98',
        adjustment_total: '0.0',
        display_adjustment_total: '$0.00',
        additional_tax_total: '0.0',
        discounted_amount: '83.98',
        display_discounted_amount: '$83.98',
        display_additional_tax_total: '$0.00',
        promo_total: '0.0',
        display_promo_total: '$0.00',
        included_tax_total: '0.0',
        display_included_tax_total: '$0.00',
        pre_tax_amount: '83.98',
        display_pre_tax_amount: '$83.98',
      },
      relationships: {variant: {data: {id: '3', type: 'variant'}}},
    },
    {
      id: '32665',
      type: 'line_item',
      attributes: {
        name: 'Long Sleeve T Shirt',
        quantity: 4,
        price: '91.99',
        slug: 'long-sleeve-t-shirt',
        options_text: '',
        currency: 'USD',
        display_price: '$91.99',
        total: '367.96',
        display_total: '$367.96',
        adjustment_total: '0.0',
        display_adjustment_total: '$0.00',
        additional_tax_total: '0.0',
        discounted_amount: '367.96',
        display_discounted_amount: '$367.96',
        display_additional_tax_total: '$0.00',
        promo_total: '0.0',
        display_promo_total: '$0.00',
        included_tax_total: '0.0',
        display_included_tax_total: '$0.00',
        pre_tax_amount: '367.96',
        display_pre_tax_amount: '$367.96',
      },
      relationships: {variant: {data: {id: '13', type: 'variant'}}},
    },
    {
      id: '32668',
      type: 'line_item',
      attributes: {
        name: 'Raw Edge T Shirt',
        quantity: 1,
        price: '76.99',
        slug: 'raw-edge-t-shirt',
        options_text: '',
        currency: 'USD',
        display_price: '$76.99',
        total: '76.99',
        display_total: '$76.99',
        adjustment_total: '0.0',
        display_adjustment_total: '$0.00',
        additional_tax_total: '0.0',
        discounted_amount: '76.99',
        display_discounted_amount: '$76.99',
        display_additional_tax_total: '$0.00',
        promo_total: '0.0',
        display_promo_total: '$0.00',
        included_tax_total: '0.0',
        display_included_tax_total: '$0.00',
        pre_tax_amount: '76.99',
        display_pre_tax_amount: '$76.99',
      },
      relationships: {variant: {data: {id: '16', type: 'variant'}}},
    },
    {
      id: '32669',
      type: 'line_item',
      attributes: {
        name: 'Polo T Shirt',
        quantity: 4,
        price: '10.99',
        slug: 'polo-t-shirt',
        options_text: '',
        currency: 'USD',
        display_price: '$10.99',
        total: '43.96',
        display_total: '$43.96',
        adjustment_total: '0.0',
        display_adjustment_total: '$0.00',
        additional_tax_total: '0.0',
        discounted_amount: '43.96',
        display_discounted_amount: '$43.96',
        display_additional_tax_total: '$0.00',
        promo_total: '0.0',
        display_promo_total: '$0.00',
        included_tax_total: '0.0',
        display_included_tax_total: '$0.00',
        pre_tax_amount: '43.96',
        display_pre_tax_amount: '$43.96',
      },
      relationships: {variant: {data: {id: '12', type: 'variant'}}},
    },
    {
      id: '32816',
      type: 'line_item',
      attributes: {
        name: 'Denim Shirt',
        quantity: 3,
        price: '60.99',
        slug: 'denim-shirt',
        options_text: '',
        currency: 'USD',
        display_price: '$60.99',
        total: '182.97',
        display_total: '$182.97',
        adjustment_total: '0.0',
        display_adjustment_total: '$0.00',
        additional_tax_total: '0.0',
        discounted_amount: '182.97',
        display_discounted_amount: '$182.97',
        display_additional_tax_total: '$0.00',
        promo_total: '0.0',
        display_promo_total: '$0.00',
        included_tax_total: '0.0',
        display_included_tax_total: '$0.00',
        pre_tax_amount: '182.97',
        display_pre_tax_amount: '$182.97',
      },
      relationships: {variant: {data: {id: '1', type: 'variant'}}},
    },
  ],
};
